import numpy as np

LOOKUP = {'ar': 'Arabic',
          'bg': 'Bulgarian',
          'de': 'German',
          'el': 'Modern Greek',
          'en': 'English',
          'es': 'Spanish',
          'fr': 'French',
          'hi': 'Hindi',
          'it': 'Italian',
          'ja': 'Japanese',
          'nl': 'Dutch',
          'pl': 'Polish',
          'pt': 'Portuguese',
          'ru': 'Russian',
          'sw': 'Swahili',
          'th': 'Thai',
          'tr': 'Turkish',
          'ur': 'Urdu',
          'vi': 'Vietnamese',
          'zh': 'Chinese'}